#!/usr/bin/env python3
"""Generate OpenMath/Collatz.lean from the collatz-modular-descent submission.

Encodes every submitted rule as Lean data and re-states the validity conditions
that the hill's own eval.py `_verify_rule` / `_load_rules` enforce, so Lean's
kernel re-checks them independently of Python.
"""
import hashlib, json, pathlib

SOL = pathlib.Path("challenges/01-openmath/collatz-modular-descent/solution/solution.json")
raw = SOL.read_bytes()
sha = hashlib.sha256(raw).hexdigest()
rules = json.loads(raw)["rules"]
lits = ",\n  ".join(
    "⟨%d, %d, [%s]⟩" % (r["modulus_power"], r["residue"], ", ".join(map(str, r["exponents"])))
    for r in rules
)
src = f'''/-
Kernel-checked certificate for the `collatz-modular-descent` submission.

Generated by OpenMath/gen_collatz.py from
  challenges/01-openmath/collatz-modular-descent/solution/solution.json
  sha256 {sha}

`ruleValid` below restates the conditions the hill's own `hill/eval.py` enforces in
`_load_rules` and `_verify_rule`: shape/range limits, the stabilisation bound
k ≥ (Σ exponents) + 1, that each step's 2-adic valuation v₂(3x+1) equals the declared
exponent, contractivity 3^steps < 2^(Σ exponents), and strict descent of the least
representative.  Lean's kernel then re-checks all {len(rules)} rules with no `native_decide`.

What this does NOT prove: that the covered classes are maximal (that argument is a
separate brute force over residue classes, done in Python), and nothing whatsoever
about the Collatz conjecture itself.
-/

namespace OpenMath.Collatz

structure Rule where
  k : Nat
  residue : Nat
  exponents : List Nat
deriving DecidableEq, Repr

/-- 2-adic valuation, fuel-bounded so it is structurally recursive. -/
def v2 : Nat → Nat → Nat
  | 0, _ => 0
  | _ + 1, 0 => 0
  | f + 1, n => if n % 2 == 0 then 1 + v2 f (n / 2) else 0

/-- Replay the accelerated trajectory, checking each declared exponent. -/
def replay (cur : Nat) : List Nat → Option Nat
  | [] => some cur
  | e :: es =>
      let n := 3 * cur + 1
      if v2 64 n == e then replay (n / 2 ^ e) es else none

def sumL : List Nat → Nat
  | [] => 0
  | a :: as => a + sumL as

def ruleValid (r : Rule) : Bool :=
  let tot := sumL r.exponents
  let steps := r.exponents.length
  (2 ≤ r.k) && (r.k ≤ 32) &&
  (r.residue % 2 == 1) && (0 < r.residue) && (r.residue < 2 ^ r.k) &&
  (1 ≤ steps) && (steps ≤ 24) &&
  (r.exponents.all fun e => (1 ≤ e) && (e ≤ 32)) &&
  (tot + 1 ≤ r.k) &&
  (3 ^ steps < 2 ^ tot) &&
  (match replay r.residue r.exponents with
   | some fin => fin < r.residue
   | none => false)

def rules : List Rule := [
  {lits}
]

/-- Every submitted rule is a genuine accelerated-Collatz descent certificate. -/
theorem all_rules_valid : rules.all ruleValid = true := by decide +kernel

theorem rule_count : rules.length = {len(rules)} := by decide +kernel

#print axioms all_rules_valid
#print axioms rule_count

end OpenMath.Collatz
'''
pathlib.Path("OpenMath/Collatz.lean").write_text(src)
print("wrote OpenMath/Collatz.lean with", len(rules), "rules, sha256", sha[:16])
