/-
Machine-checked certificate for the rank-23 decomposition of the 3x3
matrix-multiplication tensor.

GENERATED by OpenMath/gen_matmul3.py -- do not edit by hand.
Source: challenges/01-openmath/matrix-multiplication-tensor-3x3/solution/solution.json
sha256(solution.json) = 8bbae16b46963e4ed69c297ec76e9c75cc023b58c2a2a2ef7ee06786d274bb6b

Index conventions (identical to `_target` / `_check_brent` in the hill's eval.py):
  a = 3*row + inner   indexes A (row-major)
  b = 3*inner' + col  indexes B (row-major)
  c = 3*col + row     indexes C
and the certified identity is, for all a b c in 0..8,
  sum_{t<23} U[t][a] * V[t][b] * W[t][c] = if a%3 = b/3 && c = 3*(b%3) + a/3 then 1 else 0.

All theorems are closed by `decide +kernel`: the Lean kernel itself evaluates
the check by definitional reduction. No `native_decide`, so no dependence on
`Lean.ofReduceBool` / `Lean.trustCompiler`. (`brent_all` reports `propext` only;
it enters through core Int definitions, not through the proof -- `by rfl` gives the same.)

The universal statement "the bilinear algorithm equals A*B for all integer
matrices" is deliberately omitted: without Mathlib there is no `ring`, and the
729 Brent identities below are the standard equivalent certificate (they say
exactly that the two trilinear forms have equal coefficients).
-/
namespace OpenMath.MatMul3

def U : List (List Int) := [
  [1, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 0, 1, 0, 0, 0, 1, 0],
  [1, 0, 0, 0, 0, 0, (-1), 1, 0],
  [1, 0, 1, 0, 0, (-1), 0, 0, 0],
  [1, 0, 1, (-1), 0, (-1), 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 1, 0, 1],
  [0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, (-1), 0, 0, (-1), 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0],
  [0, 1, 0, 0, 0, (-1), 0, 0, 0],
  [0, 0, 0, 0, 1, (-1), 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 1, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, (-1), 0, 0, 0, 0],
  [0, 1, (-1), 0, 0, 0, 0, 0, 1],
  [0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 1, 0, 0, (-1), 0, 0, (-1)],
  [0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 1, 0, 0, 0, 0, 0, 0]]

def V : List (List Int) := [
  [1, 0, (-1), 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 1, 0, 0, 0],
  [1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, (-1)],
  [0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0, (-1)],
  [0, 1, (-1), 0, 0, (-1), 0, 0, 0],
  [1, 1, (-1), 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 1, 0, 0],
  [0, 0, 0, 1, (-1), (-1), 0, 0, 0],
  [1, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 1, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0],
  [1, 0, (-1), 0, 0, 0, (-1), 0, 1],
  [0, 1, 0, 0, 0, 0, 1, (-1), 0],
  [0, 0, 0, 0, 1, 0, 0, 1, (-1)],
  [0, 1, 0, 0, 0, 0, 0, (-1), 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1]]

def W : List (List Int) := [
  [1, 0, 1, 0, 0, 0, 0, 0, 1],
  [0, 1, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, (-1), 0, 0, 0, 0, 0, (-1)],
  [0, 0, 0, 1, 1, 0, 0, 1, 0],
  [0, 0, 0, 0, (-1), 0, 0, (-1), 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 1],
  [1, 0, 1, 0, 0, 0, 1, 0, 1],
  [0, 0, 0, 0, 0, 0, 0, (-1), 1],
  [0, 0, 0, 0, 0, 0, 0, 0, (-1)],
  [1, 1, 0, 0, 0, 0, 0, 0, 0],
  [0, (-1), 0, 0, 0, 0, 0, 0, 0],
  [0, (-1), 1, 0, 0, 0, 0, 0, 0],
  [0, (-1), 0, 1, 0, 0, 0, 0, 0],
  [0, 1, 0, 0, 1, 0, 0, 0, 0],
  [0, 1, 0, 0, 0, 1, 0, 0, 0],
  [0, (-1), 0, 0, 0, 0, 1, 0, 0],
  [0, (-1), 0, 0, 0, 0, 0, (-1), 0],
  [(-1), 0, 0, (-1), 0, 0, 0, 0, 0],
  [(-1), 0, (-1), 0, 0, 0, 0, 0, 0],
  [0, 0, 0, (-1), 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, (-1), 0, (-1), 0, 0, 0],
  [0, 0, 0, 1, 1, 0, 1, 1, 0]]

/-- Coefficient of the matrix-multiplication tensor, as in eval.py `_target`. -/
def target (a b c : Nat) : Int :=
  bif a % 3 == b / 3 && c == 3 * (b % 3) + a / 3 then 1 else 0

/-- The decomposition as a list of (u_t, v_t, w_t) triples. -/
def terms : List (List Int × List Int × List Int) := U.zip (V.zip W)

/-- sum_t u_t[a] * v_t[b] * w_t[c]. -/
def coeff (a b c : Nat) : Int :=
  terms.foldl (fun acc t => acc + t.1.getD a 0 * t.2.1.getD b 0 * t.2.2.getD c 0) 0

def idx : List Nat := [0, 1, 2, 3, 4, 5, 6, 7, 8]

/-- All 729 Brent identities. -/
def brentHolds : Bool :=
  idx.all fun a => idx.all fun b => idx.all fun c => coeff a b c == target a b c

/-- Shape and entry-range check: 23 rows of 9 entries in {-1,0,1} per factor. -/
def wellFormed : Bool :=
  [U, V, W].all fun m => m.length == 23 &&
    m.all fun r => r.length == 9 && r.all fun x => x == -1 || x == 0 || x == 1

def nnz (m : List (List Int)) : Nat :=
  m.foldl (fun acc r => r.foldl (fun acc x => if x == 0 then acc else acc + 1) acc) 0

/-- Number of nonzero entries across U, V, W (the hill's `support` metric). -/
def support : Nat := nnz U + nnz V + nnz W

def rank : Nat := terms.length

theorem brent_all : brentHolds = true := by decide +kernel

theorem well_formed : wellFormed = true := by decide +kernel

theorem rank_is_23 : rank = 23 := by decide +kernel

theorem support_is_139 : support = 139 := by decide +kernel

end OpenMath.MatMul3

#print axioms OpenMath.MatMul3.brent_all
#print axioms OpenMath.MatMul3.well_formed
#print axioms OpenMath.MatMul3.rank_is_23
#print axioms OpenMath.MatMul3.support_is_139
